version: 3

tasks:
  cover:
    desc: Show coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
      - rm coverage.out

  lint:
    desc: Lint the code
    cmds:
      - golangci-lint run

  test:
    desc: Test the code
    cmds:
      - go test -cover ./...

  workflow:
    desc: Run GitHub Actions workflow
    cmds:
      - task: lint
      - task: test
